### ISSUE TITLE
W not recognized

### ISSUE THREAD

**Issue by kubasiak** [quangnhat185/Plate_detect_and_recognize#13]
This issue I find a showstopper for me actually. 
all Ws even the ones that are clear and straight are recognized as N. I guess this is something to do with the training. 
I don't expect a solution here (but feel free to surprise me :)) but just to let you know that you might be expecting that.

**Comment by quangnhat185** [comment]
Hello @kubasiak,
The Mobilenet model which I used to train for character recognition is a lightweight architecture, which leads to the fact it might be underfitting in some scenarios. The case between W and N is a good example since in the context of computer vision, letter W is just an extend of letter N.

The solution might be to use a deeper NN such as ResNet50 or add more dataset in the categories of W and N. In the commercial product which I am working right now, we developed a YOLO detector which can detect and recognize license characters directly from plate image. This technique showed a much better accuracy due to the fact that we have really good dataset and no manual segmenting step is required.
