### ISSUE TITLE
Does the provided 1st stage model is for only detection of LP or for the Vehicle as well

### ISSUE THREAD

**Issue by Harsha-1729** [quangnhat185/Plate_detect_and_recognize#5]
Hello Quang,

Firstly thanks for your in depth article on medium.com.

Its mentioned in the Sérgio Montazzolli paper that, three main steps: 
Vehicle detection, LP detection and OCR.

My question is: 
Does the wpod-net.h5 trained model also detects the Vehicle in a given raw image or its the second stage (LP detection).

If the wpod-net.h5 is only for detecting the LP from output of 1st stage(Vehicle Detection), where can I get the trained model for Vehicle Detection.

Please let me know if anything is not clear.

Thanks 
Harsha

**Comment by quangnhat185** [comment]
Hi Harsha, 
Wpod was trained focusly on detecting the features of license plate. That is why sometimes it can mistakenly detect averstising panels on the street instead of vehicle LP.  The output of Wpod are simply 4 coordinates of the suspicious LP.

The idea solution is that you use a popular car detector such as Yolo or MobileNets-SSD to detect the car, then extract license plate from it.

There is a really good tutorial for car detecting using MobileNets-SSD which you can refer [here](https://www.pyimagesearch.com/2019/12/02/opencv-vehicle-detection-tracking-and-speed-estimation/)

**Comment by Harsha-1729** [comment]
Thank you very much for your reply :-)
