### ISSUE TITLE
Detect 0 letters

### ISSUE THREAD

**Issue by chen3082** [quangnhat185/Plate_detect_and_recognize#8]
Hey my men,
I'm trying to reproduce you project. I succeed in part1.
However, when I want to start part2, I stuck at detect 0 letters.
I used python3.7 opencv 4.2.0 numpy 1.18.5 matplotlib 3.2.2 with Jupyter notebook.
Any help would be appreciated!!!

**Comment by chen3082** [comment]
Hi, thank you so much for your amazing work.
However, after a few trying, I have two problems.
First, if I download the image myself and try to load it would occur an error in utlis.py(reconstruct).
In utlis.py line 175, it shows list index out of range. Do you have a solution to it?
Second, even if load it successfully. The segmentation isn't working very well. 
Did u manage to improve it?
Anyway, I really appreciate your work and hope you can get back to me :) .

**Comment by Harsha-1729** [comment]
> Hi, thank you so much for your amazing work.
> However, after a few trying, I have two problems.
> First, if I download the image myself and try to load it would occur an error in utlis.py(reconstruct).
> In utlis.py line 175, it shows list index out of range. Do you have a solution to it?
> Second, even if load it successfully. The segmentation isn't working very well.
> Did u manage to improve it?
> Anyway, I really appreciate your work and hope you can get back to me :) .

Hi,
The original article was taken from following link.
https://github.com/sergiomsilva/alpr-unconstrained

I think you can post your question in the above mentioned link instead of here, because the current projects deals with how to use the original project in different phases. 

I think the error is because, the network is unable to detect the 4 vertices of the License plate for the input image. Reasons may be like less size, bad environment etc. We may need to retrain the WPOD network with existing weights on our dataset to increase its capability.

I am also working on this project to complete my work. 

Regards
Harsha

**Comment by chen3082** [comment]
@Harsha-1729:
Thank you for your reply. Do you mind I ask what's your goal for this project?
I might be able to help you, I'm also trying to work on this project to complete my goal.
Currently, I'm trying to get this project to work on video or a real-time camera. 
Do you have any idea how to do so? If so, please enlighten me  :)

**Comment by Harsha-1729** [comment]
> @Harsha-1729:
> Thank you for your reply. Do you mind I ask what's your goal for this project?
> I might be able to help you, I'm also trying to work on this project to complete my goal.
> Currently, I'm trying to get this project to work on video or a real-time camera.
> Do you have any idea how to do so? If so, please enlighten me :)

@chen3082
Let us get in contact personally. you can ping me at buffy15071947@gmail.com
